name: material_things
description: Use it at your own risk!
version: 0.4.3

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  collection: ^1.19.1
  user_country_detector_android: ^0.0.1

  # We depend only on stable things like VertGap.
  flutter_things: any
  # We depend only on stable things like newLineRegExp and List<T>.regenerate.
  dart_things: any

dev_dependencies:
  freezed: ^3.0.4
  build_runner: ^2.4.15
  very_good_analysis: ^7.0.0

flutter:
  assets:
    - assets/countries.txt
    - assets/locales.txt